# Generated by Django 3.1.7 on 2022-01-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_complain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
