# Generated by Django 3.1.7 on 2022-01-20 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_complaintype'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='complainType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.complaintype'),
            preserve_default=False,
        ),
    ]
